GET  http://localhost:5000/api/passwords HTTP/1.1
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY3ZjRmYzMwNmJlYWQwNjQwYzQ3YjUyIn0sImlhdCI6MTYwMzM4MDY3MiwiZXhwIjoxNjM5MzgwNjcyfQ.mu_X2uSkZdKlTgfdvyQ9umExJPUmQr-DjA-0DW122wI

####
POST http://localhost:5000/api/passwords HTTP/1.1
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY3ZjRmYzMwNmJlYWQwNjQwYzQ3YjUyIn0sImlhdCI6MTYwMjkzMTkwNiwiZXhwIjoxNjAzMjkxOTA2fQ.AzyyASj4DW3U4UICeIVvKRAkwLI-PmqLATMccSeXDNc

{
   "service_name": "Google" ,
   "password": "123456",
   "username": "akhilbandarri9"

}
###
GET  http://localhost:5000/api/notes HTTP/1.1
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY3ZjRmYzMwNmJlYWQwNjQwYzQ3YjUyIn0sImlhdCI6MTYwNDE1NjkyMCwiZXhwIjoxNjQwMTU2OTIwfQ.wfpVSrmgsV9IYkVVCRyA4Yi0d4IB10l5swgiDHXH2vw


###
POST http://localhost:5000/api/notes HTTP/1.1
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY3ZjRmYzMwNmJlYWQwNjQwYzQ3YjUyIn0sImlhdCI6MTYwNDE1NjkyMCwiZXhwIjoxNjQwMTU2OTIwfQ.wfpVSrmgsV9IYkVVCRyA4Yi0d4IB10l5swgiDHXH2vw

{
   "title": "note Title -4" ,
   "body": "Fourth Note",
   "color":"green"
}